version: "3.9"
services:
  web:
      container_name: lweb
      image: nginx:latest
      ports:
        - 80:5100
      volumes:
        - ./:/etc/nginx/html/:ro
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      links:
        - ttyd
        - webserver
      develop:
        watch:
          - action: sync
            path: ./
            target: /
      
  vm:
    container_name: lvm
    build: ./docker/vm
  
  webserver:
    image: caddy:alpine
    ports:
      - 8080:8080
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy-data:/data
      - ./caddy-config:/config
      - .:/usr/share/caddy
    restart: always
    container_name: lwebserver

  ttyd:
    container_name: ttyd
    build: ./docker/ttyd
    command: "ttyd -W docker run -it --cpus=1 --memory=128mb --rm sendit-linux-vm"
    ports:
      - 7681:7681
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    develop:
      watch:
        - action: sync
          path: ./index.html
          target: /
        