version: "3.9"
services:
  web:
      container_name: lweb
      image: nginx:latest
      ports:
        - 5100:5100
      volumes:
        - ./:/etc/nginx/html/:ro
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      links:
        - ttyd
      develop:
        watch:
          - action: sync
            path: ./
            target: /
      
  vm:
    container_name: lvm
    build: ./docker/vm

  ttyd:
    container_name: ttyd
    build: ./docker/ttyd
    command: "ttyd -W docker run -it --cpus=1 --memory=128mb --network=none --rm sendit-linux-vm"
    ports:
      - 7681:7681
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    develop:
      watch:
        - action: sync
          path: ./index.html
          target: /
        