version: "3.9"
services:
      
  vm:
    container_name: vm
    build: ./docker/vm

  ttyd:
    container_name: ttyd
    build: ./docker/ttyd
    command: "ttyd --ssl --ssl-cert /home/dokku/linuxvm/tls/server.crt --ssl-key /home/dokku/linuxvm/tls/server.key -W docker run -it --cpus=1 --memory=128mb --network=none --rm sendit-ide-vm"
    ports:
      - 7681:7681
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock