version: "3.9"
services:
  # web:
  #   container_name: web
  #   image: nginx:latest
  #   ports:
  #     - 5100:5100
  #   volumes:
  #     - ./public:/etc/nginx/html/:ro
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   links:
  #     - ttyd
      
  vm:
    container_name: vm
    build: ./docker/vm

  ttyd:
    container_name: ttyd
    build: ./docker/ttyd
    command: "ttyd -W docker run -it --cpus=1 --memory=256mb --network=none --rm sendit-ide-vm"
    ports:
      - 7681:7681
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock